svr_config:
  name: "RMS_V3_SVR"
  host: "192.168.80.128"
  port: 8080
  mode: "dev"
  machine_id: 1

log:
  level: "debug" 
  file_name: "RMS.log"
  log_path: "./svrlog/"
  max_size: 200
  max_age: 30
  max_backups: 7
  logger_buf: "100000"

neo4j:
  host: "192.168.80.128"
  port: 7687 # Neo4j服务的Bolt URL
  username: neo4j              # 连接Neo4j的用户名
  password: zl020613      # 连接Neo4j的密码，请替换为实际密码

mysql:
  host: "192.168.80.128"
  port: 3309
  database: "user"
  username: "root"
  password: "zl020613"
  # 设置数据库连接池的最大空闲连接数为10
  max_idle_conns: 10
  
  # 设置数据库连接池的最大活跃连接数为100
  max_open_conns: 100
  
  # 设置数据库连接的最大空闲时间为10分钟
  max_idle_time: 10

jwt:
  issuer: "rms"
  jwt-salt: "rms-salt-1123"

minio:
  host: "192.168.80.128"
  port: "9000"
  access_key_id: "bYXyU6Ie9NwX9Xi5iXgo"
  secret_access_key: "LDMqHPGby44xU3QwkzxS6tTfMEjjWQ7agwtqwvSm"
  video_buckets: video
  pic_buckets: pic
  file_buckets: file
  video_path: "/home/isaac/go/video"
  pic_path: "/home/isaac/go/pic"
  file_path: "/home/isaac/go/file"
